// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/valentinesamuel/activelog/internal/repository (interfaces: ActivityRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_activity_repository.go -package=mocks github.com/valentinesamuel/activelog/internal/repository ActivityRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/valentinesamuel/activelog/internal/models"
	repository "github.com/valentinesamuel/activelog/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityRepositoryInterface is a mock of ActivityRepositoryInterface interface.
type MockActivityRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryInterfaceMockRecorder is the mock recorder for MockActivityRepositoryInterface.
type MockActivityRepositoryInterfaceMockRecorder struct {
	mock *MockActivityRepositoryInterface
}

// NewMockActivityRepositoryInterface creates a new mock instance.
func NewMockActivityRepositoryInterface(ctrl *gomock.Controller) *MockActivityRepositoryInterface {
	mock := &MockActivityRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepositoryInterface) EXPECT() *MockActivityRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockActivityRepositoryInterface) Count(userID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Count(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Count), userID)
}

// Create mocks base method.
func (m *MockActivityRepositoryInterface) Create(ctx context.Context, tx repository.TxConn, activity *models.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Create(ctx, tx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Create), ctx, tx, activity)
}

// CreateWithTags mocks base method.
func (m *MockActivityRepositoryInterface) CreateWithTags(ctx context.Context, activity *models.Activity, tags []*models.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTags", ctx, activity, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTags indicates an expected call of CreateWithTags.
func (mr *MockActivityRepositoryInterfaceMockRecorder) CreateWithTags(ctx, activity, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTags", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).CreateWithTags), ctx, activity, tags)
}

// Delete mocks base method.
func (m *MockActivityRepositoryInterface) Delete(ctx context.Context, tx repository.TxConn, id, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Delete(ctx, tx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Delete), ctx, tx, id, userID)
}

// GetActivitiesWithTags mocks base method.
func (m *MockActivityRepositoryInterface) GetActivitiesWithTags(ctx context.Context, userID int, filters models.ActivityFilters) ([]*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivitiesWithTags", ctx, userID, filters)
	ret0, _ := ret[0].([]*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivitiesWithTags indicates an expected call of GetActivitiesWithTags.
func (mr *MockActivityRepositoryInterfaceMockRecorder) GetActivitiesWithTags(ctx, userID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivitiesWithTags", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).GetActivitiesWithTags), ctx, userID, filters)
}

// GetByID mocks base method.
func (m *MockActivityRepositoryInterface) GetByID(ctx context.Context, id int64) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActivityRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).GetByID), ctx, id)
}

// GetStats mocks base method.
func (m *MockActivityRepositoryInterface) GetStats(userID int, startDate, endDate *time.Time) (*repository.ActivityStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", userID, startDate, endDate)
	ret0, _ := ret[0].(*repository.ActivityStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockActivityRepositoryInterfaceMockRecorder) GetStats(userID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).GetStats), userID, startDate, endDate)
}

// ListByUser mocks base method.
func (m *MockActivityRepositoryInterface) ListByUser(ctx context.Context, UserID int) ([]*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, UserID)
	ret0, _ := ret[0].([]*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockActivityRepositoryInterfaceMockRecorder) ListByUser(ctx, UserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).ListByUser), ctx, UserID)
}

// ListByUserWithFilters mocks base method.
func (m *MockActivityRepositoryInterface) ListByUserWithFilters(UserID int, filters models.ActivityFilters) ([]*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserWithFilters", UserID, filters)
	ret0, _ := ret[0].([]*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserWithFilters indicates an expected call of ListByUserWithFilters.
func (mr *MockActivityRepositoryInterfaceMockRecorder) ListByUserWithFilters(UserID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserWithFilters", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).ListByUserWithFilters), UserID, filters)
}

// Update mocks base method.
func (m *MockActivityRepositoryInterface) Update(ctx context.Context, tx repository.TxConn, id int, activity *models.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, id, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockActivityRepositoryInterfaceMockRecorder) Update(ctx, tx, id, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActivityRepositoryInterface)(nil).Update), ctx, tx, id, activity)
}
