// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/valentinesamuel/activelog/internal/repository (interfaces: TagRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_tag_repository.go -package=mocks github.com/valentinesamuel/activelog/internal/repository TagRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/valentinesamuel/activelog/internal/models"
	repository "github.com/valentinesamuel/activelog/internal/repository"
	query "github.com/valentinesamuel/activelog/pkg/query"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepositoryInterface is a mock of TagRepositoryInterface interface.
type MockTagRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTagRepositoryInterfaceMockRecorder is the mock recorder for MockTagRepositoryInterface.
type MockTagRepositoryInterfaceMockRecorder struct {
	mock *MockTagRepositoryInterface
}

// NewMockTagRepositoryInterface creates a new mock instance.
func NewMockTagRepositoryInterface(ctrl *gomock.Controller) *MockTagRepositoryInterface {
	mock := &MockTagRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepositoryInterface) EXPECT() *MockTagRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetOrCreateTag mocks base method.
func (m *MockTagRepositoryInterface) GetOrCreateTag(ctx context.Context, tx repository.TxConn, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateTag", ctx, tx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateTag indicates an expected call of GetOrCreateTag.
func (mr *MockTagRepositoryInterfaceMockRecorder) GetOrCreateTag(ctx, tx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateTag", reflect.TypeOf((*MockTagRepositoryInterface)(nil).GetOrCreateTag), ctx, tx, name)
}

// GetTagsForActivity mocks base method.
func (m *MockTagRepositoryInterface) GetTagsForActivity(ctx context.Context, activityID int) ([]*models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsForActivity", ctx, activityID)
	ret0, _ := ret[0].([]*models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsForActivity indicates an expected call of GetTagsForActivity.
func (mr *MockTagRepositoryInterfaceMockRecorder) GetTagsForActivity(ctx, activityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsForActivity", reflect.TypeOf((*MockTagRepositoryInterface)(nil).GetTagsForActivity), ctx, activityID)
}

// LinkActivityTag mocks base method.
func (m *MockTagRepositoryInterface) LinkActivityTag(ctx context.Context, tx repository.TxConn, activityID, tagID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkActivityTag", ctx, tx, activityID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkActivityTag indicates an expected call of LinkActivityTag.
func (mr *MockTagRepositoryInterfaceMockRecorder) LinkActivityTag(ctx, tx, activityID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkActivityTag", reflect.TypeOf((*MockTagRepositoryInterface)(nil).LinkActivityTag), ctx, tx, activityID, tagID)
}

// ListTagsWithQuery mocks base method.
func (m *MockTagRepositoryInterface) ListTagsWithQuery(ctx context.Context, opts *query.QueryOptions) (*query.PaginatedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsWithQuery", ctx, opts)
	ret0, _ := ret[0].(*query.PaginatedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsWithQuery indicates an expected call of ListTagsWithQuery.
func (mr *MockTagRepositoryInterfaceMockRecorder) ListTagsWithQuery(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsWithQuery", reflect.TypeOf((*MockTagRepositoryInterface)(nil).ListTagsWithQuery), ctx, opts)
}
