// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/valentinesamuel/activelog/internal/repository (interfaces: StatsRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_stats_repository.go -package=mocks github.com/valentinesamuel/activelog/internal/repository StatsRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/valentinesamuel/activelog/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepositoryInterface is a mock of StatsRepositoryInterface interface.
type MockStatsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryInterfaceMockRecorder is the mock recorder for MockStatsRepositoryInterface.
type MockStatsRepositoryInterfaceMockRecorder struct {
	mock *MockStatsRepositoryInterface
}

// NewMockStatsRepositoryInterface creates a new mock instance.
func NewMockStatsRepositoryInterface(ctrl *gomock.Controller) *MockStatsRepositoryInterface {
	mock := &MockStatsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepositoryInterface) EXPECT() *MockStatsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetActivityCountByType mocks base method.
func (m *MockStatsRepositoryInterface) GetActivityCountByType(ctx context.Context, userID int) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityCountByType", ctx, userID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityCountByType indicates an expected call of GetActivityCountByType.
func (mr *MockStatsRepositoryInterfaceMockRecorder) GetActivityCountByType(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityCountByType", reflect.TypeOf((*MockStatsRepositoryInterface)(nil).GetActivityCountByType), ctx, userID)
}

// GetMonthlyStats mocks base method.
func (m *MockStatsRepositoryInterface) GetMonthlyStats(ctx context.Context, userID int) (*repository.MonthlyStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyStats", ctx, userID)
	ret0, _ := ret[0].(*repository.MonthlyStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyStats indicates an expected call of GetMonthlyStats.
func (mr *MockStatsRepositoryInterfaceMockRecorder) GetMonthlyStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyStats", reflect.TypeOf((*MockStatsRepositoryInterface)(nil).GetMonthlyStats), ctx, userID)
}

// GetTopTagsByUser mocks base method.
func (m *MockStatsRepositoryInterface) GetTopTagsByUser(ctx context.Context, userID, limit int) ([]repository.TagUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopTagsByUser", ctx, userID, limit)
	ret0, _ := ret[0].([]repository.TagUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopTagsByUser indicates an expected call of GetTopTagsByUser.
func (mr *MockStatsRepositoryInterfaceMockRecorder) GetTopTagsByUser(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopTagsByUser", reflect.TypeOf((*MockStatsRepositoryInterface)(nil).GetTopTagsByUser), ctx, userID, limit)
}

// GetUserActivitySummary mocks base method.
func (m *MockStatsRepositoryInterface) GetUserActivitySummary(ctx context.Context, userID int) (*repository.UserActivitySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActivitySummary", ctx, userID)
	ret0, _ := ret[0].(*repository.UserActivitySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActivitySummary indicates an expected call of GetUserActivitySummary.
func (mr *MockStatsRepositoryInterfaceMockRecorder) GetUserActivitySummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActivitySummary", reflect.TypeOf((*MockStatsRepositoryInterface)(nil).GetUserActivitySummary), ctx, userID)
}

// GetWeeklyStats mocks base method.
func (m *MockStatsRepositoryInterface) GetWeeklyStats(ctx context.Context, userID int) (*repository.WeeklyStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeeklyStats", ctx, userID)
	ret0, _ := ret[0].(*repository.WeeklyStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeeklyStats indicates an expected call of GetWeeklyStats.
func (mr *MockStatsRepositoryInterfaceMockRecorder) GetWeeklyStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeeklyStats", reflect.TypeOf((*MockStatsRepositoryInterface)(nil).GetWeeklyStats), ctx, userID)
}
